name: prepare

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Set up NASM
        run: sudo apt-get install nasm

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Verify code formatting
        run: |
          go install mvdan.cc/gofumpt@latest
          test -z $(gofumpt -l .)

      - name: Run linter
        run: |
          go install honnef.co/go/tools/cmd/staticcheck@latest
          staticcheck ./...

      - name: Compile binaries
        run: make

      - name: Run tests with coverage
        run: go test -cover ./...

  verify-binaries:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Set up NASM
        run: sudo apt-get install nasm

      - name: Compile binaries
        run: make

      - name: Fail if binaries changed after compilation
        run: git diff --exit-code
